---
title: "Generic Lab Name"
author: "Name"
date: "Date of lab session"
output: oilabs::lab_report
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(tidyverse)
load("C:/Users/admin/Desktop/Data Wrangling/candidates.rda")
load("C:/Users/admin/Desktop/Data Wrangling/contributions.rda")
load("C:/Users/admin/Desktop/Data Wrangling/house_elections.rda")
load("C:/Users/admin/Desktop/Data Wrangling/individuals.rda")

```

* * *

### Exercise 1: 

```{r}

glimpse(committees)
glimpse(house_elections)

committees <- committees %>%
  select(cmte_id, cmte_name, cmte_state, cmte_type, cmte_party_affiliation, cand_id) %>%
  filter(cmte_party_affiliation == "REP" | cmte_party_affiliation == "DEM")

house_elections <- house_elections %>%
  select(fec_id, candidate_name, incumbent, party, ge_winner) %>%
  filter(party == "D" | party == "R") %>%
  rename(cand_id = fec_id)

house_elections$party[house_elections$party == "R"] <- "REP"
house_elections$party[house_elections$party == "D"] <- "DEM"

  
```



```{r}

candidates <- candidates %>%
  select(cand_id, cand_name, cand_party_affiliation, cand_election_yr, cand_office_state, cand_office, cand_office_district, cand_ici) %>%
  filter(cand_party_affiliation == "DEM" | cand_party_affiliation == "REP")

```



```{r}

contributions <- contributions %>%
  filter(amndt_ind == "N", memo_cd != "X", transaction_type != "24A", transaction_type != "24N") %>%
  select(cmte_id, entity_type, transaction_amt, other_id, cand_id)
  

```



```{r}

house_contributions <- house_elections %>%
  left_join(contributions, by = "cand_id") %>%
  group_by(cand_id, candidate_name) %>%
  summarize(total_amt = sum(transaction_amt))

View(house_contributions)
View(house_elections)


```

```{r}
house_elections <- house_elections %>%
  left_join(house_contributions, by = "cand_id") %>%
  select(-candidate_name.y) %>%
  rename(candidate_name = candidate_name.x) %>%
  filter(!is.na(total_amt)) %>%
  arrange(desc(total_amt))


```


```{r}

incumbent_plot <- ggplot(house_elections, aes(y = total_amt, x = incumbent)) + geom_boxplot(aes(color = party, fill = party))

winner_plot <- ggplot(house_elections, aes(y = total_amt, x = ge_winner)) + geom_boxplot(aes(color = party, fill = party))

incumbent_plot
winner_plot

```

```{r}

individuals <- individuals %>%
  select(cmte_id, name, transaction_type, transaction_amt) %>%
  group_by(cmte_id, transaction_type) %>%
  summarize(no_of_contributions = n(), total_indiv_amt = sum(transaction_amt))

```

```{r}

committees <- committees %>%
  left_join(individuals, by = "cmte_id")

```

Comparing National Republican Congressional Committee (NRCC) and Democratic Congressional Campaign Committee (DCCC):

```{r}

hill_committees <- committees %>%
  filter(cmte_id == "C00075820" | cmte_id == "C00000935" | cmte_id == "C00027466" | cmte_id == "C00042366") %>%
  group_by(cmte_name) %>%
  summarize(total_no_of_contributions = sum(no_of_contributions), total_indiv_contributions = sum(total_indiv_amt))

```
 
4 major Hill Committees' individual contributions for 2011-2012 cycle:

```{r}

indiv_contribution_plot <- ggplot(hill_committees, aes(y = total_indiv_contributions, x = cmte_name, fill = cmte_name)) + geom_bar(stat = "identity") + scale_fill_manual(values=c("cornflowerblue", "blue", "pink", "red"))

indiv_contribution_plot

```

4 major Hill Committees' number of individual contributions for 2011-2012 cycle:

```{r}

contribution_number_plot <- ggplot(hill_committees, aes(y = total_no_of_contributions, x = cmte_name, fill = cmte_name)) + geom_bar(stat = "identity") + scale_fill_manual(values=c("cornflowerblue", "blue", "pink", "red"))

contribution_number_plot

```


